### ISSUE TITLE
What about pre-release?

### ISSUE THREAD

**Issue by minecrawler** [staltz/comver#2]
When I am still working on my code, it should be 0.x, however pre-release APIs tend to change a lot, so what is the best way to communicate pre-release versions?

In SemVer, I dropped the patch-version and used [minor] as major and [patch] as minor, changing a `x.y.z` to `0.x.y`

**Comment by staltz** [comment]
ComVer only communicates compatibility or incompatibility. If you want to communicate any other aspect, use a changelog. A package following ComVer should start at 1.0, even if it's considered a draft and not ready for production. You should communicate that it's not ready for production in the changelog.

**Comment by neverfox** [comment]
Yeah, I think the problem is the 0.y.0 convention for pre-releases, not ComVer. Instead, I think library authors just shouldn't release a version without hyphenated pre-release info because they exist to communicate "this API is in flux" and "no claims are currently being made about compatibility in the current version number". So rather than releasing 0.0.1, 0.1.0, or 0.2.0 etc., you release 1.0-SNAPSHOT (and let something like Maven assign a unique tag for each change to that) or 1.0-1, 1.0-alpha1. Then you're saying, "we're working on 1.0, but until then all we're claiming is that 1.0-alpha1 and 1.0-alpha2 are different and one came out after the other". Likewise, if 1.0 is out, and someone wants to know what they can conclude about 2.0-SNAPSHOT, the answer is same. It might end up resulting in a release of 1.1 or it might in up resulting in a release of 2.0, but that hasn't been determined.
